AllCops:
  TargetRubyVersion: 2.6.5
  NewCops: enable

Layout/LineLength:
  IgnoredPatterns: ['^#']
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'


Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

#Layout/HashAlignment:
#  EnforcedColonStyle:

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/DoubleNegation:
  Enabled: false
